### ISSUE TITLE
making link you are on visible

### ISSUE THREAD

**Issue by plsgivemeramen** [plsgivemeramen/CDGD-304-01#6]
have link be a different color when on it

**Comment by saulbaizman** [comment]
Did you try add a class to that specific link? For example, see below:

```html
<a href="page1.html">About</a>
<a href="page2.html" class="current_page">Contact</a>
<a href="page3.html">Gallery</a>
```

Then you'd create a CSS selector like so:

```css
a.current_page {
color: green ;
/* blah blah blah */
}
```
